// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Student struct {
	ID           int32
	Name         sql.NullString
	StudentCode  sql.NullString
	Gender       sql.NullString
	Dob          sql.NullString
	DobFormat    sql.NullString
	Class        sql.NullString
	ClassCode    sql.NullString
	Ethnic       sql.NullString
	NationalID   sql.NullString
	Phone        sql.NullString
	Email        sql.NullString
	Province     sql.NullString
	Address      sql.NullString
	Notes        sql.NullString
	SearchVector interface{}
}
