version: "3.8"

services:
  discordbot:
    build: .
    container_name: discordbot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - SERVER_ID=${SERVER_ID}
    restart: unless-stopped
