services:
  discordbot:
    build: .
    container_name: discordbot
    env_file:
      - .env
    environment:
      - PRODUCTION=TRUE
    restart: unless-stopped
    networks:
      - pg-network
    volumes:
      - bot_data:/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
networks:
  pg-network:
    external: true # Only if you created it manually
volumes:
  bot_data:
